# Create User

POST http://localhost:3000/api/user
content-type: application/json

{
  "email": "dummy@gmail.com",
  "password": "testing"
}

### Login

POST http://localhost:3000/api/login
content-type: application/json

{
  "email": "dummy@gmail.com",
  "password": "testing"
}
